service: miranda-backend
frameworkVersion: "3"
package:
  patterns:
    - "!./**"
    - "package.json"
    - "node_modules/**"
    - "dist/**"
    - "data/**"
    - "index.html"
provider:
  name: aws
  region: eu-west-3
  
  runtime: nodejs18.x
functions:
  app:
    handler: dist/lambda.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true