name: Deploy Node-express-app

on:
  push:
    branches:
    - main

jobs:
    deploy:
        name: deploy
        runs-on: ubuntu-latest        
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js v18.18.0
              uses: actions/setup-node@v4
              with:
                node-version: v18.18.0
            - name: Install requeriments
              run: npm install
            - name: Build the project
              run: npm run build
            - name: serverless deploy
              uses: serverless/github-action@v3.2
              with:
                args: deploy
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   